import { useEffect, useState } from "react";
import axios from "axios";

function App() {
  const [word, setWord] = useState("");

  const url = "https://api.dictionaryapi.dev/api/v2/entries/en_US/";

  // const [error, loading] = customReactQuery(url, word);

  // if (error) {
  //   return <h1>Something Went Wrong!</h1>;
  // }

  // if (loading) {
  //   return <h1>Loading...</h1>;
  // }

  // Component rerendering check
  // useEffect(() => {
  //   // console.log("Component Rerendered");
  //   handleSubmit();
  // }, [handleSubmit]);

  // // handle submit function to call the API
  // async function handleSubmit() {
  //   try {
  //     const response = await axios.get(url + word);
  //     console.log(response.data); //0.meanings[0].definitions
  //     // setData(response.data);
  //   } catch (error) {
  //     console.error("Error fetching data:", error);
  //   }
  // }

  // handle submit function to call the API using form
  async function handleSubmit(e) {
    e.preventDefault();

    try {
      const response = await axios.get(url + word);
      console.log(response.data);
    } catch (error) {
      console.log("Error fetching data:", error);
    }
  }

  return (
    <>
      {/* <input
        className="border-2 border-black"
        type="text"
        placeholder="Search any word"
        value={word}
        onChange={(e) => setWord(e.target.value)}
      />
      <button onSubmit={handleSubmit} type="submit">
        Search
      </button> */}

      {/* NOW USING FORM */}

      <form onSubmit={handleSubmit}>
        <input
          className="border-2 border-black"
          type="text"
          value={word}
          onChange={(e) => setWord(e.target.value)}
          placeholder="Enter a word"
        />
        <button type="submit">Search</button>
      </form>

      {/* {error && <h1>Something Went Wrong!</h1>}
      {loading && <h1>Loading...</h1>} */}
      {/* <div className="logo">
        <h1>WORD</h1>
      </div>
      <header>
        <input type="text" placeholder="Search any word..." />
        <button type="submit">Search</button>
      </header>
      <div className="word">
        <h2>Random Word for you</h2>
        <h1>transpire</h1>

        <p>
          To give off (vapour, waste matter etc.); to exhale (an odour etc.). To
          perspire. Of plants, to give off water and waste products through the
          stomata. To become known; to escape from secrecy. To happen, take
          place.
        </p>
      </div> */}
    </>
  );
}

export default App;

// const customReactQuery = (url, word) => {
//   const [error, setError] = useState(false);
//   const [loading, setLoading] = useState(false);

//   useEffect(() => {
//     const controller = new AbortController();
//     (async () => {
//       try {
//         setLoading(true);
//         setError(false);
//         // simulate delay - remove in production (generated by copilot)
//         await new Promise((resolve) => setTimeout(resolve, 1500));

//         const response = await axios.get(url + word, {
//           signal: controller.signal,
//         });
//         console.log(response.data); //0.meanings[0].definitions
//         setLoading(false);
//       } catch (error) {
//         if (axios.isCancel(error)) {
//           console.log("Request Cancelled");
//         } else {
//           console.error("API call failed", error); // Log the error
//           setError(true);
//         }
//         setLoading(false);
//       }
//     })();

//     return () => controller.abort();
//   }, [word]);

//   return [error, loading];
// };
