// importing components
import Navbar from "./components/Navbar";
import Definitions from "./components/Definitions";
import Synonyms from "./components/Synonyms";
import Footer from "./components/Footer";

// importing context and useState
import { useState } from "react";
import { DictionaryContext } from "./context/context";

function App() {
  const [data, setData] = useState([]);
  // -------------- DELETE: Previous code that did not worked  -------------------------
  // const [error, loading] = customReactQuery(url, word);

  // if (error) {
  //   return <h1>Something Went Wrong!</h1>;
  // }

  // if (loading) {
  //   return <h1>Loading...</h1>;
  // }

  // Component rerendering check
  // useEffect(() => {
  //   // console.log("Component Rerendered");
  //   handleSubmit();
  // }, [handleSubmit]);

  // // handle submit function to call the API
  // async function handleSubmit() {
  //   try {
  //     const response = await axios.get(url + word);
  //     console.log(response.data); //0.meanings[0].definitions
  //     // setData(response.data);
  //   } catch (error) {
  //     console.error("Error fetching data:", error);
  //   }
  // }
  // -----------------------------------------------------------------------

  // handle submit function to call the API using form
  return (
    <DictionaryContext.Provider value={[setData, data]}>
      <div className="max-w-screen-lg">
        {/* ---------- DELETE: Previous code that did not worked ------- */}
        {/* <input
        className="border-2 border-black"
        type="text"
        placeholder="Search any word"
        value={word}
        onChange={(e) => setWord(e.target.value)}
      />
      <button onSubmit={handleSubmit} type="submit">
        Search
      </button> */}
        {/* ------------------------------------------------------- */}

        {/* NOW USING FORM IN THE NAVBAR COMPONENT*/}
        <Navbar />

        <div className="dictionary md:flex">
          {/* DEFINTIONS COMPONENT */}
          <Definitions />

          {/* SYNONYMS COMPONENT */}
          <Synonyms />
        </div>

        {/* FOOTER COMPONENT */}
        <Footer />

        {/* 0.meanings[1].synonyms */}

        {/* ---------- DELETE: Previous code that did not worked ------- */}
        {/* {error && <h1>Something Went Wrong!</h1>}
      {loading && <h1>Loading...</h1>} */}
        {/* <div className="logo">
        <h1>WORD</h1>
      </div>
      <header>
        <input type="text" placeholder="Search any word..." />
        <button type="submit">Search</button>
      </header>
      <div className="word">
        <h2>Random Word for you</h2>
        <h1>transpire</h1>

        <p>
        To give off (vapour, waste matter etc.); to exhale (an odour etc.). To
        perspire. Of plants, to give off water and waste products through the
        stomata. To become known; to escape from secrecy. To happen, take
        place.
        </p>
      </div> */}
        {/* ---------------------------------------------------------------- */}
      </div>
    </DictionaryContext.Provider>
  );
}

export default App;

// -------------- DELETE: Previous code that did not worked  -------------------------
// const customReactQuery = (url, word) => {
//   const [error, setError] = useState(false);
//   const [loading, setLoading] = useState(false);

//   useEffect(() => {
//     const controller = new AbortController();
//     (async () => {
//       try {
//         setLoading(true);
//         setError(false);
//         // simulate delay - remove in production (generated by copilot)
//         await new Promise((resolve) => setTimeout(resolve, 1500));

//         const response = await axios.get(url + word, {
//           signal: controller.signal,
//         });
//         console.log(response.data); //0.meanings[0].definitions
//         setLoading(false);
//       } catch (error) {
//         if (axios.isCancel(error)) {
//           console.log("Request Cancelled");
//         } else {
//           console.error("API call failed", error); // Log the error
//           setError(true);
//         }
//         setLoading(false);
//       }
//     })();

//     return () => controller.abort();
//   }, [word]);

//   return [error, loading];
// };
// -----------------------------------------------------------------------
